### ISSUE TITLE
IPversion field in ADD_ADDRESS-frame

### ISSUE THREAD

**Issue by The3ternum** [qdeconinck/draft-deconinck-multipath-quic#9]
In the draft you explain the format of the ADD_ADDRESS-frame, specifically the IPVersion field: "The remaining four bits in the first byte of this frame represent the version of the IP address contained in a later field." Is there a specific reason as to why four bits are used? And how are the different versions represented?

**Comment by qdeconinck** [comment]
The IPVersion field follows the same formatting as the Version field in the IP header. As it uses 4 bits, we reuse the same space and encoding.

**Comment by The3ternum** [comment]
Thank you for your answer!
